version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - make test
    - go generate ./...
    - go mod tidy
    - go mod download

builds:
  - id: nvdexp
    main: ./cmd/nvdexp
    binary: nvdexp
    flags:
      - -tags=release
      - -buildmode=default
      - -trimpath
      - -v
    ldflags:
      - "-X github.com/dosquad/go-cliversion.BuildDate={{ .Date }}"
      - "-X github.com/dosquad/go-cliversion.BuildDebug=false"
      - "-X github.com/dosquad/go-cliversion.BuildMethod=goreleaser"
      - "-X github.com/dosquad/go-cliversion.BuildVersion={{.Version}}"
      - "-X github.com/dosquad/go-cliversion.GitCommit={{.ShortCommit}}"
      - '-X github.com/dosquad/go-cliversion.GitRepo={{.GitURL}}'
      - '-X github.com/dosquad/go-cliversion.GitSlug={{- $gitsa := split (trimsuffix .GitURL ".git") ":" -}}{{- $gitsp := split (index $gitsa 1) "/" -}}{{- $size := len $gitsp -}}{{- $sla := len (slice (printf "%*s" $size "") 2) -}}{{ $slb := len (slice (printf "%*s" $size "") 1) -}}{{index $gitsp $sla}}/{{index $gitsp $slb}}'
      - "-X github.com/dosquad/go-cliversion.GitTag={{.Version}}"
      - "-X github.com/dosquad/go-cliversion.GitExactTag={{.RawVersion}}"
      - "-X main.commit={{.ShortCommit}}"
      - "-X main.date={{ .Date }}"
      - "-X main.builtBy=goreleaser"
      - "-X main.repo={{.GitURL}}"
      - "-X main.goVersion=1.22.4"
      - "-X main.version={{.Version}}"
      - "-s"
      - "-w"
    mod_timestamp: '{{ .CommitTimestamp }}'
    goarm: [ '5', '6', '7' ]
    goos: ['linux', 'darwin', 'windows']
    goarch: ['amd64', 'arm', 'arm64']
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - allow_different_binary_count: true

checksum:
  algorithm: sha256
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    id: nvdexplorer
    package_name: nvdexplorer
    file_name_template: "nvdexplorer_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    builds:
      - nvdexp
    homepage: https://github.com/na4ma4/nvdexplorer
    maintainer: na4ma4 <na4ma4@users.noreply.github.com>
    description: NVD Explorer
    formats:
      - apk
      - deb
    bindir: /usr/bin
